#!/bin/bash
set -e

BUILD_DIR='dist'

if [ ! -e "$BUILD_DIR"/.git ] ; then
  rm -rf "$BUILD_DIR"
  git worktree add "$BUILD_DIR" gh-pages
fi

cd "$BUILD_DIR"
git add .
git commit -em 'Deploy to GitHub Pages'
git push origin gh-pages
